### ISSUE TITLE
I'm having a problem with agents initializing

### ISSUE THREAD

**Issue by Mrmichelerocha** [fetchai/uAgents#172]
### Discussed in https://github.com/fetchai/uAgents/discussions/171

<div type='discussions-op-text'>

<sup>Originally posted by **Mrmichelerocha** September 23, 2023</sup>
Hi, I'm using agents for my course completion work, making an extension to the BDI architecture widely used in multi-agents, and today I went to compile my agents and they gave the following problem:

```
Traceback (most recent call last):
   File "C:\Users\mggrl\Documents\ag-bdi_central\agent1.py", line 9, in <module>
     central = Create_agent.Central()
   File "C:\Users\mggrl\Documents\ag-bdi_central\aumanaque.py", line 39, in Central
     fund_agent_if_low(central.wallet.address())
   File "C:\Users\mggrl\Documents\ag-bdi_central\uAgents\src\uagents\setup.py", line 20, in fund_agent_if_low
     faucet.get_wealth(agent_address)
   File "C:\Users\mggrl\AppData\Local\pypoetry\Cache\virtualenvs\uagents-Hie5aemw-py3.9\lib\site-packages\cosmpy\aerial\faucet.py", line 154, in get_wealth
     raise RuntimeError(f"Failed to get wealth for {address}")
RuntimeError: Failed to get wealth for fetch1twvhcnk7tdr08vsree7z0phj244vhfzvqwm3a6
```

Can you give me a little help?</div>

**Comment by jrriehl** [comment]
Yes, there is currently a problem with the Dorado testnet faucet that we are working to fix. It should be working again soon.

**Comment by jrriehl** [comment]
The testnet faucet was out of funds but it was replenished so things should be working again now. Let us know if you have any more issues.
