### ISSUE TITLE
Bug in agent example readme.md

### ISSUE THREAD

**Issue by tomekstrzeszkowski** [fetchai/uAgents#395]
Seems the context doesn't have `name` attribute
```
ERROR:    [alice]: Exception in interval handler: 'InternalContext' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/tomasz.strzeszkowski/.pyenv/versions/3.11.2/lib/python3.11/site-packages/uagents/agent.py", line 73, in _run_interval
    await func(ctx)
  File "<stdin>", line 3, in say_hello
AttributeError: 'InternalContext' object has no attribute 'name'
```

it should call `context.agent.name`

[PR](https://github.com/fetchai/uAgents/pull/396) for that

**Comment by Archento** [comment]
PR has been merged.
Thanks again for your contribution!
