### ISSUE TITLE
Getting Errors with Agents Broadcast Example

### ISSUE THREAD

**Issue by bhavsar1997** [fetchai/uAgents#558]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/uAgents/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Expected Behavior

- It should continue broadcasting the messages. But this started producing errors after 3/4 minutes. 
- As its a self hosted environment I shouldn't get any errors w.r.t. agentverse. But I can see some error logs with text "agentverse".

### Observed Behavior

It started properly by registering the agents on almanac.
They communicated as expected
Below error produced after 3 minutes:

`INFO:     [charles]: Received response from agent1q0mau8vkmg78xx0sh8cyl4tpl4ktx94pqp2e94cylu6haugt2hd7j9vequ7: Hello from bob
INFO:     [charles]: Received response from agent1qww3ju3h6kfcuqf54gkghvt2pqe8qp97a7nzm2vp8plfxflc0epzcjsv79t: Hello from alice
INFO:     [charles]: Trying to contact 2 agents.
INFO:     [charles]: Received response from agent1q0mau8vkmg78xx0sh8cyl4tpl4ktx94pqp2e94cylu6haugt2hd7j9vequ7: Hello from bob
INFO:     [charles]: Received response from agent1qww3ju3h6kfcuqf54gkghvt2pqe8qp97a7nzm2vp8plfxflc0epzcjsv79t: Hello from alice
INFO:     [charles]: Trying to contact 2 agents.
ERROR:    [charles]: OS Error in interval handler: HTTPSConnectionPool(host='agentverse.ai', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/home/hp/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/hp/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hp/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/hp/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "/home/hp/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/hp/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/hp/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/hp/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/hp/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='agentverse.ai', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hp/.local/lib/python3.9/site-packages/uagents/agent.py", line 73, in _run_interval
    await func(ctx)
  File "/home/hp/Documents/fetch/agent-bases-p2p-trading/agents/trading-agent-v3/test_braodcast.py", line 34, in say_hello
    status_list = await ctx.broadcast(proto.digest, message=BroadcastExampleRequest())
  File "/home/hp/.local/lib/python3.9/site-packages/uagents/context.py", line 360, in broadcast
    agents = self.get_agents_by_protocol(
  File "/home/hp/.local/lib/python3.9/site-packages/uagents/context.py", line 342, in get_agents_by_protocol
    response = requests.post(
  File "/home/hp/.local/lib/python3.9/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/hp/.local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hp/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hp/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/hp/.local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='agentverse.ai', port=443): Read timed out. (read timeout=30)
ERROR:    [charles]: No active agents found for: proto:5ec877056f701fdbae45bc2fe702adb58a502c81a7ba8c0d65c58998725544e5
INFO:     [charles]: Trying to contact 0 agents.
ERROR:    [charles]: No active agents found for: proto:5ec877056f701fdbae45bc2fe702adb58a502c81a7ba8c0d65c58998725544e5
INFO:     [charles]: Trying to contact 0 agents.`

### To Reproduce

- Simply Copied the example from [https://fetch.ai/docs/examples/intermediate/broadcast](url)
- Executed in a python environment with uagents version : 0.14.0

### Version

v0.14.0

**Comment by bhavsar1997** [comment]
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='agentverse.ai', port=443): Read timed out. (read timeout=30)

Why the host is agentverse? It should be my local I believe.

**Comment by Archento** [comment]
The errors that you're seeing are not related to `ctx.broadcast()` and are coming up because the agent could not establish a connection to the Agentverse.

To increase availability, robustness and speed of the registration we've implemented an alternative registration mechanism that is hosted at `agentverse.ai` which fast tracks the registration on the Almanac smart contract.

Please also make sure to always use the latest version of uagents which is now `v0.16.2` with a new release just around the corner.

If the error persists or you still see unexpected error messages, feel free to open another issue.
Thank you
